### ISSUE TITLE
正式网链ID

### ISSUE THREAD

**Issue by wrenfix** [Orbiter-Finance/openapi-example#1]
![image](https://github.com/Orbiter-Finance/openapi-example/assets/63827365/c79578f3-1a00-4982-b3d9-68dc5b5cddf3)

求一个正式网链ID，没有找到正式网的链ID列表，主要想取到发送跨链交易时的识别码

**Comment by Tq101510** [comment]
Can you make it English []()

**Comment by kakui-lau** [comment]
https://docs.orbiter.finance/developer/rest-api/overview

here has
